notifications:
  email: false
dist: xenial
os: linux
language: python
python: 3.8-dev
cache: pip
env:
  global:
    - GH_REPO=Drakkar-Software/OctoBot-CLI
    - DEPLOY_BRANCH=master
    - PACKAGE_FOLDER=octobot_cli

install:
  - python3 -m pip install --prefer-binary -r dev_requirements.txt -r requirements.txt

jobs:
  include:
    - name: "Linux - Python 3.8 - Python sources"
      stage: test
      script:
        - pytest --cov=. --cov-config=.coveragerc --durations=0 -rw tests
      after_success:
        - if [ $TRAVIS_PULL_REQUEST == "false" ]; then coveralls; fi

    - name: "Linux - Python 3 - Deploy"
      stage: deploy
      script:
        - ls
      deploy:
        - provider: pypi
          username: __token__
          password:
            secure: fxXKIbmqamwvGo13eFPcVXc0owziPyRxZqscdHI/ELdKifO9smOuk5dOpEEPY9zo0p2sE05w/7WP1ArK9TIJdlUHB90OksWQ9+/COgsj/AePXv6Z1VtVeBRB1nWk0HKIN71UjTrPp/os9eekFM+Myj6bluTWLp7iYznQXxw/MJd3UFL4upMHjnX/7q/bZpAn6rQ/cYvsRyFvOJlB9FVuwrYIMhTvakUFBBGpIKg2sbr6MRVPX9IwHRB6l9FCpw7RzEC49xUe5pMXbcunmfzVpxH198ttdTy6+2BRe4aNZYqaBDbZagvUUMwNxSQ577Ikq3OWyTJv/ZRqUCzMXSccgHumCzt7d0o0Y3ptdNZ5Kg3cEMULFwI718rDTNdDK00P5usYhrVztm6iEAeM/t1LXwbY5IAlbk/rEqtkBH6lC1xYNpU9V6nJuORxVbgWnKmPYtaeKuo/rsHrrSLNasBsD/jU9kAURz++tR7KX/MXNi6W4iWYReKHJ5g3OjqWnSH4FitwAnPSB5ty8HEKG7K+BseRNF+2kmBQtgwLT8/f7mlRL87NwVdFv6CDbnW6cK/HXLdtqzVQXyDv9ThW+1dxHoYHS2nMJPt0ep+upAXyK2umEf+ShJj87OUqvQGsoLDLLI2qBD47fAYq7xE26/0h5WzQMLZRHpGucejs5OMXC10=
          skip_existing: true
          cleanup: true
          distributions: "sdist"
          on:
            repo: $GH_REPO
            branch: $DEPLOY_BRANCH
            tags: true

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure https://discordapp.com/api/webhooks/$WEBHOOK_TOKEN
